services:
  - type: web
    name: jps-api-server
    env: python
    plan: free  # Tier gratuito
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"  # Inicia con Gunicorn
    numInstances: 1
    healthCheckPath: /get_result  # Opcional, para check de salud
